import { expect, test } from "@playwright/test";

test("manual goal creates a preview, adopts a plan, replaces one meal and reopens the saved revision", async ({page}) => {
  await page.goto("/");
  await page.getByLabel("每日熱量（kcal）").fill("2000");
  await page.getByLabel("每日蛋白質（g）").fill("100");
  await page.getByRole("button",{name:"檢查目標"}).click();
  await page.getByRole("button",{name:"確認使用此目標"}).click();
  await expect(page.getByRole("region",{name:"安排三天餐單"})).toBeVisible();
  await page.getByLabel("開始日期").fill("2026-10-01");
  await page.getByRole("button",{name:"產生三天提案"}).click();
  const preview = page.getByRole("region",{name:"餐單提案預覽"});
  await expect(preview).toBeVisible();
  await expect(page.getByRole("region",{name:"已採用餐單"})).toHaveCount(0);
  await page.getByRole("button",{name:"採用這份提案"}).click();
  const adopted = page.getByRole("region",{name:"已採用餐單"});
  await expect(adopted).toContainText("已保存 · 版本 1");
  await expect(preview).toHaveCount(0);
  await expect(page.getByRole("region",{name:"採買清單"})).toBeVisible();
  await adopted.getByRole("button",{name:"換菜"}).first().click();
  await expect(preview).toBeVisible();
  await expect(adopted).toContainText("已保存 · 版本 1");
  await page.getByRole("button",{name:"取消提案"}).click();
  await expect(preview).toHaveCount(0);
  await adopted.getByRole("button",{name:"換菜"}).first().click();
  await page.getByRole("button",{name:"採用這份提案"}).click();
  await expect(adopted).toContainText("已保存 · 版本 2");
  const meals = await adopted.getByTestId("meal-name").allTextContents();
  await page.reload();
  await expect(adopted).toContainText("已保存 · 版本 2");
  expect(await adopted.getByTestId("meal-name").allTextContents()).toEqual(meals);
  const portion = adopted.getByLabel("2026-10-01 早餐份量");
  const quantity = await portion.inputValue() === "1.5" ? "1.25" : "1.5";
  await portion.fill(quantity);
  await adopted.getByRole("button",{name:"更新份量"}).first().click();
  await expect(adopted).toContainText("已保存 · 版本 3");
  await expect(adopted.getByRole("article").first()).toContainText(quantity === "1.25" ? "本餐熱量：500 kcal" : "本餐熱量：600 kcal");
  await adopted.getByRole("button",{name:"鎖定",exact:true}).first().click();
  await expect(adopted).toContainText("已保存 · 版本 4");
  const shopping = adopted.getByRole("region",{name:"採買清單"}).getByRole("checkbox").first();
  await shopping.click();
  await expect(adopted).toContainText("已保存 · 版本 5");
  await adopted.getByRole("button",{name:"復原上一版"}).click();
  await expect(adopted).toContainText("已保存 · 版本 6");
  await expect(shopping).not.toBeChecked();
  await page.route("**/api/plan/actions",route => route.fulfill({status:503,json:{error:"storage_unavailable"}}));
  await page.route("**/api/plan",route => route.fulfill({status:503,json:{error:"storage_unavailable"}}));
  await shopping.click();
  await expect(adopted).toContainText("唯讀快照 · 版本 6");
  await expect(shopping).not.toBeChecked();
  await expect(shopping).toBeDisabled();
  await page.unroute("**/api/plan/actions");await page.unroute("**/api/plan");
  await page.getByRole("button",{name:"重新讀取餐單"}).click();
  await expect(adopted).toContainText("已保存 · 版本 6");
  await page.route("**/api/plan/preview",route => route.fulfill({status:503,json:{error:"calculation_unavailable"}}));
  await adopted.getByRole("button",{name:"換菜"}).nth(1).click();
  await expect(page.getByRole("alert")).toContainText("提案未完成");
  await shopping.click();
  await expect(adopted).toContainText("已保存 · 版本 7");
  await page.route("**/api/session",route => route.fulfill({status:503,json:{error:"storage_unavailable"}}));
  await page.route("**/api/plan",route => route.fulfill({status:503,json:{error:"storage_unavailable"}}));
  await page.getByRole("button",{name:"清除本次規劃"}).click();
  await expect(adopted).toContainText("唯讀快照 · 版本 7");
  await expect(page.getByRole("alert")).toContainText("清除尚未確認");
  await page.unroute("**/api/session");await page.unroute("**/api/plan");
  await page.getByRole("button",{name:"清除本次規劃"}).click();
  await expect(adopted).toHaveCount(0);
  await page.reload();
  await expect(adopted).toHaveCount(0);
});

test("guided estimation reaches the same preview and saved goal contract", async ({page}) => {
  await page.goto("/");
  await page.getByRole("button",{name:"幫我設定目標"}).click();
  await page.getByLabel("年齡（歲）").fill("30");
  await page.getByLabel("身高（cm）").fill("170");
  await page.getByLabel("體重（kg）").fill("70");
  await page.getByLabel("公式分類").selectOption("male");
  await page.getByRole("combobox",{name:"活動分級"}).selectOption("inactive");
  await page.getByLabel("飲食目標").selectOption("maintain");
  await page.getByLabel("規律訓練").selectOption("false");
  await page.getByLabel("孕期或哺乳期").selectOption("false");
  await page.getByLabel("需要專業調整飲食").selectOption("false");
  await page.getByRole("button",{name:"在本機估算"}).click();
  await expect(page.getByRole("region",{name:"目標預覽"})).toBeVisible();
  await page.getByLabel("每日熱量（kcal）").fill("2000");
  await page.getByLabel("每日蛋白質（g）").fill("100");
  await page.getByRole("button",{name:"檢查目標"}).click();
  await page.getByRole("button",{name:"確認使用此目標"}).click();
  await expect(page.getByTestId("confirmed-goal")).toContainText("使用者調整估算");
  await page.getByLabel("開始日期").fill("2026-10-01");
  await page.getByRole("button",{name:"產生三天提案"}).click();
  await page.getByRole("button",{name:"採用這份提案"}).click();
  await expect(page.getByRole("region",{name:"已採用餐單"})).toContainText("已保存 · 版本 1");
  const state = await page.evaluate(async () => (await fetch("/api/plan")).json());
  expect(state.current.candidate.goal.source).toBe("user_adjusted");
  expect(state.current.candidate.goal.requested.kcal).toBe(2000);
  expect(state.current.candidate.goal).not.toHaveProperty("weightKg");
  expect(state.current.candidate.goal).not.toHaveProperty("age");
});

test("fixed breakfast external unknowns and confirmed pantry reach the saved plan", async ({page}) => {
  await page.goto("/");
  await page.getByLabel("每日熱量（kcal）").fill("2000");
  await page.getByLabel("每日蛋白質（g）").fill("100");
  await page.getByRole("button",{name:"檢查目標"}).click();
  await page.getByRole("button",{name:"確認使用此目標"}).click();
  await page.getByLabel("開始日期").fill("2026-10-01");
  await page.getByLabel("固定三天早餐").selectOption("oat-yogurt");
  await page.getByLabel("外食名稱").fill("使用者提供的外食");
  await page.getByLabel("外食餐次").selectOption("lunch");
  await page.getByRole("button",{name:"加入固定外食"}).click();
  const pantrySelect = page.getByLabel("庫存食材");
  const oats = await pantrySelect.locator("option").filter({hasText:"燕麥"}).first().getAttribute("value");
  await pantrySelect.selectOption(oats!);
  await expect(page.getByLabel("庫存單位")).toBeVisible();
  await page.getByLabel("庫存單位").selectOption("kg");
  await page.getByLabel("庫存數量",{exact:true}).fill("0.1");
  await page.getByLabel("已確認庫存數量").check();
  await page.getByRole("button",{name:"加入庫存"}).click();
  await page.getByRole("button",{name:"產生三天提案"}).click();
  const preview = page.getByRole("region",{name:"餐單提案預覽"});
  await expect(preview).toContainText("資料不完整");
  await expect(preview).toContainText("庫存扣抵 100");
  await page.getByRole("button",{name:"採用這份提案"}).click();
  await expect(page.getByRole("region",{name:"已採用餐單"})).toContainText("已保存 · 版本 1");
  const state = await page.evaluate(async () => (await fetch("/api/plan")).json());
  expect(state.current.candidate.meals.filter((meal: {recipeId: string}) => meal.recipeId === "oat-yogurt")).toHaveLength(3);
  expect(state.current.candidate.meals.find((meal: {kind: string}) => meal.kind === "external").locked).toBe(true);
  expect(state.current.shopping.items.find((item: {foodId: string}) => item.foodId === "oats").pantryUsed).toBe(100);
  await page.getByText("生活條件、固定餐點與庫存",{exact:true}).click();
  await page.getByRole("button",{name:"移除庫存",exact:true}).click();
  await page.getByRole("button",{name:"產生三天提案"}).click();
  await page.getByRole("button",{name:"採用這份提案"}).click();
  const adopted = page.getByRole("region",{name:"已採用餐單"});
  await expect(adopted).toContainText("已保存 · 版本 2");
  await adopted.getByRole("button",{name:"復原上一版"}).click();
  await expect(adopted).toContainText("已保存 · 版本 3");
  await page.getByText("生活條件、固定餐點與庫存",{exact:true}).click();
  await expect(page.getByRole("region",{name:"安排三天餐單"})).toContainText("燕麥：0.1 kg／已確認");
  await page.getByRole("button",{name:"產生三天提案"}).click();
  await expect(preview).toContainText("庫存扣抵 100");
});

test("saved workspace stays within desktop and mobile widths", async ({page}) => {
  await page.setViewportSize({width:1360,height:1000});
  await page.goto("/");
  await page.getByRole("button",{name:"載入合成目標"}).click();
  await page.getByRole("button",{name:"確認使用此目標"}).click();
  await page.getByLabel("開始日期").fill("2026-10-01");
  await page.getByRole("button",{name:"產生三天提案"}).click();
  await page.getByRole("button",{name:"採用這份提案"}).click();
  const adopted = page.getByRole("region",{name:"已採用餐單"});
  await expect(adopted).toContainText("已保存 · 版本 1");
  await adopted.evaluate(element => element.scrollIntoView({block:"start"}));
  await page.screenshot({path:"../../.artifacts/t08-desktop.png"});
  expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(1360);
  await page.setViewportSize({width:390,height:844});
  await adopted.evaluate(element => element.scrollIntoView({block:"start"}));
  await page.screenshot({path:"../../.artifacts/t08-mobile.png"});
  expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(390);
  await adopted.getByRole("button",{name:"換菜"}).first().focus();
  await expect(adopted.getByRole("button",{name:"換菜"}).first()).toBeFocused();
});

test("unsupported saved snapshots require an explicit new plan", async ({page}) => {
  await page.route("**/api/plan",route => route.fulfill({status:409,contentType:"application/json",body:JSON.stringify({error:"unsupported_state"})}));
  let creates = 0;
  page.on("request", request => {if (request.url().endsWith("/api/session") && request.method() === "POST") creates++;});
  await page.goto("/");
  await expect(page.getByRole("alert")).toContainText("舊餐單格式");
  expect(creates).toBe(0);
  await page.getByRole("button",{name:"開始新規劃"}).click();
  await expect(page.getByText("目前為唯讀狀態。")).toHaveCount(0);
  await expect(page.getByRole("button",{name:"清除本次規劃"})).toBeVisible();
  expect(creates).toBe(1);
});

for (const recovery of ["reload","conflict"] as const) {
  test(`${recovery} synchronizes goal and preferences from the recovered snapshot`, async ({page}) => {
    await page.goto("/");
    await page.getByRole("button",{name:"載入合成目標"}).click();
    await page.getByRole("button",{name:"確認使用此目標"}).click();
    await page.getByRole("button",{name:"產生三天提案"}).click();
    await page.getByRole("button",{name:"採用這份提案"}).click();
    const adopted = page.getByRole("region",{name:"已採用餐單"});
    await expect(adopted).toContainText("已保存 · 版本 1");
    const remote = await page.evaluate(async () => (await fetch("/api/plan")).json());
    remote.revision = 2;
    remote.current.candidate.goal.requested.kcal = 1800;
    remote.current.candidate.goal.ranges.kcal = {min:1710,max:1890};
    remote.current.candidate.constraints.preferredFoods = ["oats"];
    remote.current.candidate.constraints.slots = ["lunch"];
    remote.current.candidate.constraints.equipment = ["pot"];
    await page.route("**/api/plan",route => route.fulfill({json:remote}));
    if (recovery === "reload") await page.getByRole("button",{name:"重新讀取餐單"}).click();
    else {
      await page.route("**/api/plan/actions",route => route.fulfill({status:409,json:{error:"revision_conflict"}}));
      await adopted.getByRole("button",{name:"鎖定",exact:true}).first().click();
    }
    await expect(adopted).toContainText("已保存 · 版本 2");
    await page.getByText("生活條件、固定餐點與庫存",{exact:true}).click();
    let goal: unknown;
    await page.route("**/api/plan/preview",route => {goal = route.request().postDataJSON().goal;return route.fulfill({status:503,json:{error:"calculation_unavailable"}});});
    await page.getByRole("button",{name:"產生三天提案"}).click();
    await expect(page.getByRole("alert")).toContainText("提案未完成");
    expect(goal).toMatchObject({requested:{kcal:1800}});
    await expect(page.getByLabel("早餐",{exact:true})).not.toBeChecked();
    await expect(page.getByLabel("鍋具",{exact:true})).toBeChecked();
    await expect(page.getByLabel("偏好食材（逗號分隔）")).toHaveValue(/oats|燕麥/);

  });
}

test("Chinese food exclusions resolve to catalog identifiers before preview", async ({page}) => {
  await page.goto("/");
  await page.getByRole("button",{name:"載入合成目標"}).click();
  await page.getByRole("button",{name:"確認使用此目標"}).click();
  await page.getByLabel("排除食材（逗號分隔）").fill("燕麥");
  let excluded: unknown;
  await page.route("**/api/plan/preview",route => {excluded = route.request().postDataJSON().constraints.excludedFoods;return route.fulfill({status:503,json:{error:"calculation_unavailable"}});});
  await page.getByRole("button",{name:"產生三天提案"}).click();
  await expect(page.getByRole("alert")).toContainText("提案未完成");
  expect(excluded).toEqual(["oats"]);
  excluded = undefined;
  await page.getByLabel("排除食材（逗號分隔）").fill("尚未收錄的食材");
  await page.getByRole("button",{name:"產生三天提案"}).click();
  await expect(page.getByRole("alert").filter({hasText:"無法確認食材"})).toBeVisible();
  expect(excluded).toBeUndefined();
});

test("Agent produces two separate previews and only the chosen round is adopted", async ({page}) => {
  await page.goto("/");
  await page.getByRole("button",{name:"載入合成目標"}).click();
  await page.getByRole("button",{name:"確認使用此目標"}).click();
  await page.getByLabel("開始日期").fill("2026-10-01");
  await page.getByRole("button",{name:"設定條件並開啟對話"}).click();
  const chat = page.getByRole("region",{name:"備餐對話"});
  await expect(chat).toBeVisible();
  await chat.getByLabel("想如何安排餐點？").fill("請安排三天餐單");
  await chat.getByRole("button",{name:"傳送"}).click();
  const preview = page.getByRole("region",{name:"餐單提案預覽"});
  await expect(preview).toBeVisible();
  const first = await page.evaluate(async () => (await fetch("/api/plan")).json());
  expect(first.current).toBeNull();
  await chat.getByLabel("想如何安排餐點？").fill("請重新提出三天餐單，先不要採用");
  await chat.getByRole("button",{name:"傳送"}).click();
  await expect(chat.getByRole("status")).toContainText("提案已完成");
  await expect(preview).toBeVisible();
  await page.setViewportSize({width:1440,height:1000});
  await preview.scrollIntoViewIfNeeded();
  await page.screenshot({path:"../../.artifacts/t09-chat-desktop.png"});
  await page.setViewportSize({width:390,height:844});
  await chat.scrollIntoViewIfNeeded();
  await expect(page.locator("body")).toHaveJSProperty("scrollWidth",390);
  await page.screenshot({path:"../../.artifacts/t09-chat-mobile.png"});
  await page.getByRole("button",{name:"採用這份提案"}).click();
  await expect(page.getByRole("region",{name:"已採用餐單"})).toContainText("已保存 · 版本 1");
});
